### ISSUE TITLE
Linking FMOD libraries should not be required

### ISSUE THREAD

**Issue by GitGhillie** [lebedec/libfmod#14]
Hi! I'm making a plugin for FMOD, for which it's basically only necessary to create a library which exports `extern "C" fn FMODGetDSPDescription() -> *mut FMOD_DSP_DESCRIPTION`.

At first I made my own quick-and-dirty bindings for FMOD and I was successfully able to build the plugin and load it in FMOD Studio.

Then I realized the wonderful `libfmod` already has the bindings I need (but better) and I switched my code over to that. However now my build fails with:
```
  = note: /usr/bin/ld: cannot find -lfmod: No such file or directory
          /usr/bin/ld: cannot find -lfmodstudio: No such file or directory
          collect2: error: ld returned 1 exit status
```

This is not my area of expertise but it seems like the build script of libfmod is doing stuff which is not necessary for my case. Would it be possible to make it optional (but on by default) with a feature flag?

**Comment by lebedec** [comment]
Hi! Technically this is possible. We can change the [build.rs](https://github.com/lebedec/libfmod/blob/main/libfmod/build.rs) script, say, introduce a new environment variable that will disable linking instructions.

But I'm not sure it is right way. A `libfmod` generated for each FMOD version because of different versions of FMOD contain incompatible definitions. At linking stage this problem eliminated by linker which match all definitions.

Imagine you wrote a plugin for FMOD 2.02 and then tried to load it into FMOD 2.01 or 2.03. If in these versions the fields of `FMOD_DSP_DESCRIPTION` structure have changed or the name of the functions has changed, nothing will work.

As I understand it, the FMOD [documentation](https://fmod.com/docs/2.00/api/white-papers-dsp-plugin-api.html#accessing-plug-ins-in-fmod-studio) also says this:

```
A plug-in must be built as a dynamic linked library and placed in the plug-ins folder ...
```

So, I think you should simply provide FMOD libraries for linking one of the way:

```
ln -s ~/FMOD20220/api/core/lib/libfmod.so /usr/local/lib/libfmod.so
ln -s ~/FMOD20220/api/studio/lib/libfmodstudio.so /usr/local/lib/libfmodstudio.so

export LD_LIBRARY_PATH=~/FMOD20220/api/studio/lib
```

Or you can provide more sources (examples or articles) where described how FMOD plugins works, especially with bindings (when you want to use FMOD structures or functions in your plugins).

**Comment by GitGhillie** [comment]
> Imagine you wrote a plugin for FMOD 2.02 and then tried to load it into FMOD 2.01 or 2.03. If in these versions the fields of FMOD_DSP_DESCRIPTION structure have changed or the name of the functions has changed, nothing will work.

I think that's why the first member of `FMOD_DSP_DESCRIPTION` is the SDK version:
`
The first member, [FMOD_DSP_DESCRIPTION::pluginsdkversion](https://www.fmod.com/docs/2.00/api/plugin-api-dsp.html#fmod_dsp_description_pluginsdkversion), must always hold the version number of the plug-in SDK it was complied with. This version is defined as FMOD_PLUGIN_SDK_VERSION. The SDK version is incremented whenever changes to the API occur.
`
(From [this](https://www.fmod.com/docs/2.00/api/white-papers-dsp-plugin-api.html#the-plug-in-descriptor) section).

fwiw when I use a local copy of `libfmod` with the build script commented out, I'm able to create myplugin.so and place it into a Plugins folder of my FMOD project, and I can successfully load it. When I manually change  `pluginsdkversion: FMOD_PLUGIN_SDK_VERSION` to a different version I get this in my FMOD Studio console: 
```
09:26:21 Error loading plugin /home/GitGhillie/Projects/steam-audio-rewrite/fmod-project/Plugins/myplugin.so: A plugin was built with an unsupported SDK version. 
```
So I think it's safe to rely on that

**Comment by lebedec** [comment]
Look at note from your documentation link:

The first member `pluginsdkversion` must always hold the **version number of the plug-in SDK it was complied with**.

It means what `FMOD_PLUGIN_SDK_VERSION` defined in FMOD SDK headers will generated in `libfmod` correspondently. For me it make more sense to not provide any FMOD app or plugin without linking with concrete FMOD version library.

Why I so concerned about that? =) 

Because FMOD team makes are breaking backward compatibility changes even between minor versions. For example, there are changes between FMOD 2.06.06 and 2.02.20 that are incompatible. You have same FMOD plugin version, same major version, but different definitions of few structures. Catching SEGFAULT and maintaining such problems in runtime is very painful and costly. Not big deal if it single case. But what will happen if `libmod` is used in many projects on different versions of FMOD?

My interest here is to avoid "unnecessary" support of `libfmod` because of such problems =) What why one of main design concept of `libfmod` is easy providing exact binding for exact FMOD version to eliminate any mismatches in API definitions.

I think ignoring this problem, providing plugin without linking with exact version of FMOD is simply postponing the technical issue until later, when fixing it will probably be a bigger problem. 

Are you still sure that you need to disable linking?

**Comment by GitGhillie** [comment]
Let's use a concrete example so we don't go in circles.

(btw feel free to yeet this issue if it's taking too much of your time, it's a very minor issue after all).

Here is a very minimal but working plugin which can be loaded into FMOD Studio:
https://gist.github.com/GitGhillie/86d04ba4cba2c7ce03e4a2ee3be4f322

A few notes:
- It does not call any FMOD functions (i.e. only the header files are needed, not the FMOD dynamic libs).
- It only exports `FMODGetDSPDescription()` which is called by FMOD Studio when loading the plugin.
- I used `libfmod = "~2.222"`, so `FMOD_PLUGIN_SDK_VERSION` and all the structs I'm using are all defined within libfmod's ffi.rs.
- Whether I use the build script or not, the resulting dylib (which can be loaded into FMOD Studio) remains the same in size.
- If I build the plugin using libfmod 2.222, I can load it with the FMOD Studio version I have currently installed. Say a new version of FMOD Studio comes out with breaking changes in the API, FMOD will catch this when loading the plugin (this I have shown in my previous comment). There is no segfault and the solution would simply be to update the plugin with the latest version of libfmod and build the plugin again.

So I guess my question is, what does linking actually do when my plugin does not call any FMOD functions?

**Comment by lebedec** [comment]
Your concrete example is fine. But I want consider this issue for all future usage of `libfmod`, not just for your concrete example.

I have already managed to catch the real problems I describe. If you don't believe me, you can compare the versions 2.02.06 and 2.02.20. They have same major version, same FMOD_PLUGIN_SDK_VERSION 110, but different definitions of same structs, enum, etc. It means that FMOD_PLUGIN_SDK_VERSION maybe control plugin API or DSP definitions, but not catch all FMOD API changes in fact (your rely on this mechanism is not safe, unfortunately). 

So, linking here acts as additional effective issue guard, not version checker.

And as a maintainer of `libfmod` I want to be sure what new changes (even it optional configuration of build) do not provide support issues in other projects and scenarios for other users. I don't want investigate problems of people just because they have different version of FMOD by mistake or not =) 

Can you guarantee what other plugins (not yours) will not call any FMOD functions or struct definitions? I'm not sure, maybe is not needed (or not possible at all) in plugin development?

So... Now I see two ways to solve this issue:

* I am ready to make linking optional only if it is absolutely necessary and correct. My point and concerns I described. Maybe you can provide your motivation why you just not link your plugin? 
* We can make better design of `libfmod` if you can provide information about FMOD plugin development (my questions above). For example, put everything that is needed specifically for plugins into a separate crate without linking.

**Comment by GitGhillie** [comment]
Since a plugin is just something that describes how audio samples should be transformed, I don't see why FMOD functions need to be called, and I don't think a plugin has access to the FMOD context. Otherwise you could just add a custom dsp as shown [here](https://github.com/lebedec/libfmod/blob/main/libfmod/tests/examples/core.rs) with the FMOD libs linked.

Anyways I don't have the experience to say for sure, and I haven't found anything in the docs that is clear on this.

> I am ready to make linking optional only if it is absolutely necessary and correct. My point and concerns I described. Maybe you can provide your motivation why you just not link your plugin?

It's not necessary to make linking optional but at the same time linking does absolutely nothing in my case. So it feels wrong that I now have to add instructions to my plugin crate on how to download and install the FMOD libs just to get it to compile. (I'll probably just refer to this crate though).

> We can make better design of libfmod if you can provide information about FMOD plugin development (my questions above). For example, put everything that is needed specifically for plugins into a separate crate without linking.

Unfortunately I don't think FMOD has a clear separation/indication on what exactly is related to plugin development...

Since your stance is clear and there is not enough clarity from the FMOD side I will close this issue for now
